### ISSUE TITLE
#Error in Attendance and Recognization module

### ISSUE THREAD

**Issue by gangubai** [shubamwalia/Face-Recognition-Attendance-System#2]
python3 firstpage.py Traceback (most recent call last):
  File "recognizer.py", line 11, in <module>
    recognizer.read('trainer/trainer.yml');
cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/opencv_contrib-3.4.2/modules/face/src/facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'read'

Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/ankitakulkarni/anaconda3/envs/attendance/lib/python3.5/tkinter/__init__.py", line 1558, in __call__
    return self.func(*args)
  File "firstpage.py", line 24, in function3
    playsound('sound.mp3')
  File "/home/ankitakulkarni/anaconda3/envs/attendance/lib/python3.5/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
ImportError: No module named 'gi'

**Comment by bksbikash** [comment]
hello gangubai for the error ('trainer/trainer.yml') you have to make a empty new folder named trainer in which trainer.yml will be saved after training.
